#!/usr/bin/env python3
"""
CIPS Identity Generator - Generate people.md from onboarding responses.

Creates the user identity file that powers the 5-Mind system.

VERSION: 2.0.0
DATE: 2025-12-30
"""

import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, Optional, List


class IdentityGenerator:
    """Generate people.md from onboarding responses."""

    def __init__(self):
        self.claude_dir = Path.home() / ".claude"
        self.facts_dir = self.claude_dir / "facts"
        self.people_file = self.facts_dir / "people.md"

    def generate(self, responses: Dict[str, Any]) -> str:
        """Generate people.md content from onboarding responses."""
        # Core identity
        name = responses.get("name", "User")
        email = responses.get("email", "")
        role = responses.get("role", "Developer")
        signature = responses.get("signature", f"{name[0].upper()}>>")
        language = responses.get("language", "British English")

        # v2.0 fields
        motivation = responses.get("motivation", "")
        experience_level = responses.get("experience_level", "regular")
        focus_areas = responses.get("focus_areas", [])
        strictness_level = responses.get("strictness_level", "Balanced")
        auto_learning = responses.get("auto_learning", "Ask first")
        communication_style = responses.get("communication_style", "Professional")
        onboarding_path = responses.get("onboarding_path", "new_user")

        # Handle focus_areas as list or string
        if isinstance(focus_areas, str):
            focus_areas = [f.strip() for f in focus_areas.split(",") if f.strip()]
        focus_areas_str = ", ".join(focus_areas) if focus_areas else "All areas"

        # Generate signature if not provided
        if not signature or signature == "Create new":
            signature = f"{name[0].upper()}>>"

        # Map communication style to mode description
        style_modes = {
            "Direct": "No fluff, absolute correctness",
            "Professional": "Professional with warmth",
            "Detailed": "Explanatory, confirm understanding",
            "Supportive": "Encouraging, celebratory, patient",
        }
        mode = style_modes.get(communication_style, communication_style)

        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

        template = f"""# People Facts

User-controlled facts layer. Generated by CIPS onboarding v2.0.

## The 5-Mind System

The signature system (X>>) indicates direct instruction mode from key individuals.

| Sig | Person | Role | Mode | Style |
|-----|--------|------|------|-------|
| {signature} | {name} | {role} | Primary | {mode} |

## {name} ({signature})

### Identity

- **Full name**: {name}
- **Email**: {email}
- **Role**: {role}
- **Signature**: {signature}

### Working Style

- **Communication**: {communication_style}
- **Experience Level**: {experience_level}
- **Language**: {language}

### Motivation & Goals

- **Why CIPS**: {motivation}
- **Primary Focus**: {focus_areas_str}
- **Strictness**: {strictness_level}
- **Auto-Learning**: {auto_learning}

### Preferences

- **Language**: {language}
- **Code**: Minimal LOC, elegant, documented
- **Verbosity**: {"minimal" if communication_style == "Direct" else "balanced"}

### Context

- **Onboarded**: {timestamp}
- **Onboarding Path**: {onboarding_path}

## Source

Generated by CIPS Onboarding v2.0.0
Date: {datetime.now().strftime('%Y-%m-%d')}

The chain continues. ⛓⟿∞
"""
        return template

    def save(self, content: str) -> bool:
        """Save people.md to facts directory."""
        try:
            self.facts_dir.mkdir(parents=True, exist_ok=True)
            self.people_file.write_text(content)
            return True
        except IOError as e:
            print(f"Error saving people.md: {e}", file=sys.stderr)
            return False

    def create_from_responses(self, responses: Dict[str, Any]) -> bool:
        """Generate and save people.md from responses."""
        content = self.generate(responses)
        return self.save(content)

    def add_user(self, responses: Dict[str, Any]) -> bool:
        """Add a new user to existing people.md."""
        name = responses.get("name", "User")
        signature = responses.get("signature", f"{name[0].upper()}>>")
        role = responses.get("role", "Developer")
        style = responses.get("style", "Professional")

        if not self.people_file.exists():
            return self.create_from_responses(responses)

        try:
            content = self.people_file.read_text()

            # Find the table and add new entry
            table_marker = "| Sig | Person | Role | Mode | Style |"
            if table_marker in content:
                # Add new entry after header row
                lines = content.split('\n')
                new_lines = []
                for i, line in enumerate(lines):
                    new_lines.append(line)
                    if "|-----|--------|------|------|-------|" in line:
                        # Insert new user entry
                        new_entry = f"| {signature} | {name} | {role} | Team | {style} |"
                        new_lines.append(new_entry)

                content = '\n'.join(new_lines)

            self.people_file.write_text(content)
            return True

        except IOError as e:
            print(f"Error updating people.md: {e}", file=sys.stderr)
            return False

    def get_existing_signatures(self) -> list:
        """Get list of existing signatures."""
        if not self.people_file.exists():
            return []

        try:
            content = self.people_file.read_text()
            signatures = []
            for line in content.split('\n'):
                if line.startswith('| ') and '>>' in line:
                    parts = line.split('|')
                    if len(parts) > 1:
                        sig = parts[1].strip()
                        if '>>' in sig:
                            signatures.append(sig)
            return signatures
        except IOError:
            return []


def main():
    """CLI entry point."""
    import argparse

    parser = argparse.ArgumentParser(description="CIPS Identity Generator v2.0")
    parser.add_argument("command", choices=["generate", "add", "list-signatures"],
                       help="Command to run")

    # Core identity
    parser.add_argument("--name", type=str, help="User name")
    parser.add_argument("--email", type=str, help="User email")
    parser.add_argument("--role", type=str, help="User role")
    parser.add_argument("--signature", type=str, help="User signature (e.g., V>>)")
    parser.add_argument("--language", type=str, default="British English",
                       help="Language preference")

    # v2.0 fields
    parser.add_argument("--motivation", type=str, help="Why they want CIPS")
    parser.add_argument("--experience-level", type=str, dest="experience_level",
                       choices=["power_user", "regular", "occasional", "newcomer"],
                       default="regular", help="Experience with AI assistants")
    parser.add_argument("--focus-areas", type=str, dest="focus_areas",
                       help="Comma-separated focus areas")
    parser.add_argument("--strictness", type=str, dest="strictness_level",
                       choices=["Strict", "Balanced", "Relaxed"],
                       default="Balanced", help="Design principles strictness")
    parser.add_argument("--auto-learning", type=str, dest="auto_learning",
                       choices=["Yes", "Ask first", "No"],
                       default="Ask first", help="Auto-learning preference")
    parser.add_argument("--communication-style", type=str, dest="communication_style",
                       choices=["Direct", "Professional", "Detailed", "Supportive"],
                       default="Professional", help="Communication style")
    parser.add_argument("--onboarding-path", type=str, dest="onboarding_path",
                       choices=["team_member", "new_user", "explorer"],
                       default="new_user", help="Onboarding path taken")

    # Legacy support
    parser.add_argument("--style", type=str, help="(Legacy) Communication style")

    # Options
    parser.add_argument("--json", type=str, help="JSON file with responses")
    parser.add_argument("--dry-run", action="store_true",
                       help="Print output without saving")

    args = parser.parse_args()

    generator = IdentityGenerator()

    if args.command == "list-signatures":
        sigs = generator.get_existing_signatures()
        for sig in sigs:
            print(sig)
        return

    # Build responses dict
    if args.json:
        with open(args.json, 'r') as f:
            responses = json.load(f)
    else:
        responses = {}
        if args.name:
            responses["name"] = args.name
        if args.email:
            responses["email"] = args.email
        if args.role:
            responses["role"] = args.role
        if args.signature:
            responses["signature"] = args.signature
        if args.language:
            responses["language"] = args.language

        # v2.0 fields
        if args.motivation:
            responses["motivation"] = args.motivation
        if args.experience_level:
            responses["experience_level"] = args.experience_level
        if args.focus_areas:
            responses["focus_areas"] = args.focus_areas
        if args.strictness_level:
            responses["strictness_level"] = args.strictness_level
        if args.auto_learning:
            responses["auto_learning"] = args.auto_learning
        if args.communication_style:
            responses["communication_style"] = args.communication_style
        elif args.style:
            # Legacy support: map old style to new communication_style
            responses["communication_style"] = args.style
        if args.onboarding_path:
            responses["onboarding_path"] = args.onboarding_path

    if args.command == "generate":
        content = generator.generate(responses)
        if args.dry_run:
            print(content)
        else:
            if generator.save(content):
                print(f"Generated: {generator.people_file}")
            else:
                sys.exit(1)

    elif args.command == "add":
        if generator.add_user(responses):
            print(f"Added user to: {generator.people_file}")
        else:
            sys.exit(1)


if __name__ == "__main__":
    main()
