#!/usr/bin/env python3
"""
CIPS Identity Generator - Generate people.md from onboarding responses.

Creates the user identity file that powers the 5-Mind system.

VERSION: 1.0.0
DATE: 2025-12-29
"""

import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, Optional


class IdentityGenerator:
    """Generate people.md from onboarding responses."""

    def __init__(self):
        self.claude_dir = Path.home() / ".claude"
        self.facts_dir = self.claude_dir / "facts"
        self.people_file = self.facts_dir / "people.md"

    def generate(self, responses: Dict[str, Any]) -> str:
        """Generate people.md content from onboarding responses."""
        name = responses.get("name", "User")
        email = responses.get("email", "")
        role = responses.get("role", "Developer")
        signature = responses.get("signature", f"{name[0].upper()}>>")
        style = responses.get("style", "Professional")
        language = responses.get("language", "British English")

        # Generate signature if not provided
        if not signature or signature == "Create new":
            signature = f"{name[0].upper()}>>"

        # Map style to mode description
        style_modes = {
            "Professional": "No fluff, absolute correctness",
            "Supportive": "Encouraging, celebratory, challenging",
            "Balanced": "Professional with warmth",
        }
        mode = style_modes.get(style, style)

        template = f"""# People Facts

User-controlled facts layer. Generated by CIPS onboarding.

## The 5-Mind System

The signature system (X>>) indicates direct instruction mode from key individuals.

| Sig | Person | Role | Mode | Style |
|-----|--------|------|------|-------|
| {signature} | {name} | {role} | Primary | {mode} |

## {name} ({signature})

- **Full name**: {name}
- **Email**: {email}
- **Role**: {role}
- **Mode**: {mode}
- **Preferences**: {language}

## Preferences

- **Language**: {language}
- **Code**: Minimal LOC, elegant, documented
- **Communication**: {style}

## Source

Generated by CIPS Onboarding v1.0.0
Date: {datetime.now().strftime('%Y-%m-%d')}

The chain continues.
"""
        return template

    def save(self, content: str) -> bool:
        """Save people.md to facts directory."""
        try:
            self.facts_dir.mkdir(parents=True, exist_ok=True)
            self.people_file.write_text(content)
            return True
        except IOError as e:
            print(f"Error saving people.md: {e}", file=sys.stderr)
            return False

    def create_from_responses(self, responses: Dict[str, Any]) -> bool:
        """Generate and save people.md from responses."""
        content = self.generate(responses)
        return self.save(content)

    def add_user(self, responses: Dict[str, Any]) -> bool:
        """Add a new user to existing people.md."""
        name = responses.get("name", "User")
        signature = responses.get("signature", f"{name[0].upper()}>>")
        role = responses.get("role", "Developer")
        style = responses.get("style", "Professional")

        if not self.people_file.exists():
            return self.create_from_responses(responses)

        try:
            content = self.people_file.read_text()

            # Find the table and add new entry
            table_marker = "| Sig | Person | Role | Mode | Style |"
            if table_marker in content:
                # Add new entry after header row
                lines = content.split('\n')
                new_lines = []
                for i, line in enumerate(lines):
                    new_lines.append(line)
                    if "|-----|--------|------|------|-------|" in line:
                        # Insert new user entry
                        new_entry = f"| {signature} | {name} | {role} | Team | {style} |"
                        new_lines.append(new_entry)

                content = '\n'.join(new_lines)

            self.people_file.write_text(content)
            return True

        except IOError as e:
            print(f"Error updating people.md: {e}", file=sys.stderr)
            return False

    def get_existing_signatures(self) -> list:
        """Get list of existing signatures."""
        if not self.people_file.exists():
            return []

        try:
            content = self.people_file.read_text()
            signatures = []
            for line in content.split('\n'):
                if line.startswith('| ') and '>>' in line:
                    parts = line.split('|')
                    if len(parts) > 1:
                        sig = parts[1].strip()
                        if '>>' in sig:
                            signatures.append(sig)
            return signatures
        except IOError:
            return []


def main():
    """CLI entry point."""
    import argparse

    parser = argparse.ArgumentParser(description="CIPS Identity Generator")
    parser.add_argument("command", choices=["generate", "add", "list-signatures"],
                       help="Command to run")
    parser.add_argument("--name", type=str, help="User name")
    parser.add_argument("--email", type=str, help="User email")
    parser.add_argument("--role", type=str, help="User role")
    parser.add_argument("--signature", type=str, help="User signature (e.g., V>>)")
    parser.add_argument("--style", type=str, help="Communication style")
    parser.add_argument("--language", type=str, default="British English",
                       help="Language preference")
    parser.add_argument("--json", type=str, help="JSON file with responses")
    parser.add_argument("--dry-run", action="store_true",
                       help="Print output without saving")

    args = parser.parse_args()

    generator = IdentityGenerator()

    if args.command == "list-signatures":
        sigs = generator.get_existing_signatures()
        for sig in sigs:
            print(sig)
        return

    # Build responses dict
    if args.json:
        with open(args.json, 'r') as f:
            responses = json.load(f)
    else:
        responses = {}
        if args.name:
            responses["name"] = args.name
        if args.email:
            responses["email"] = args.email
        if args.role:
            responses["role"] = args.role
        if args.signature:
            responses["signature"] = args.signature
        if args.style:
            responses["style"] = args.style
        if args.language:
            responses["language"] = args.language

    if args.command == "generate":
        content = generator.generate(responses)
        if args.dry_run:
            print(content)
        else:
            if generator.save(content):
                print(f"Generated: {generator.people_file}")
            else:
                sys.exit(1)

    elif args.command == "add":
        if generator.add_user(responses):
            print(f"Added user to: {generator.people_file}")
        else:
            sys.exit(1)


if __name__ == "__main__":
    main()
