#!/bin/bash
# Auto-generated command wrapper for {{SKILL_NAME}} skill
# Generated by self-improvement-engine on {{CREATION_DATE}}
#
# Usage: /{{COMMAND_NAME}} [args...]
#
# Description: {{COMMAND_DESCRIPTION}}

set -euo pipefail

SKILL_NAME="{{SKILL_NAME}}"
SKILL_PATH="$HOME/.claude/skills/$SKILL_NAME/SKILL.md"

# Verify skill exists
if [[ ! -f "$SKILL_PATH" ]]; then
    echo "Error: Skill '$SKILL_NAME' not found at $SKILL_PATH" >&2
    exit 1
fi

# Parse arguments
ARGS="$*"

# {{COMMAND_LOGIC}}

# Invoke Claude Code with skill context
# Note: This is a reference implementation - actual slash command integration
# happens through Claude Code's command system, not via bash scripts
echo "Activating skill: $SKILL_NAME"
echo "Arguments: $ARGS"
echo "Skill path: $SKILL_PATH"

{{CUSTOM_COMMAND_LOGIC}}

exit 0
